//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EXACTUSEntities : DbContext
    {
        public EXACTUSEntities()
            : base("name=EXACTUSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<XTUS_AUDITORIA_AFFIDAVIT> XTUS_AUDITORIA_AFFIDAVIT { get; set; }
        public DbSet<XTUS_Rol> XTUS_Rol { get; set; }
        public DbSet<XTUS_USUARIO> XTUS_USUARIO { get; set; }
        public DbSet<XTUS_DatoGeneral> XTUS_DatoGeneral { get; set; }
        public DbSet<XTUS_DatoGeneralDetalle> XTUS_DatoGeneralDetalle { get; set; }
    }
}
